"""init users table

Revision ID: 37fbff02c763
Revises: 
Create Date: 2026-09-11 16:56:04.568047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Alembic 修订版本标识
revision: str = '37fbff02c763'
# 上一修订版本（None 表示首个版本）
down_revision: Union[str, None] = None
# 分支标签，多分支并行迁移时使用
branch_labels: Union[str, Sequence[str], None] = None
# 依赖的其他修订版本
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移：正向执行表结构变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码哈希'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚迁移：逆序撤销 upgrade 的变更。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
